/* tslint:disable */
/* eslint-disable */
/**
 * Cria Embed API
 * API for embedding Cria into web-pages on the world wide interwebs!
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

