name: CI

on: 
  push:
    branches:
      - main
      - feature/criaembed-ragflow-elastic

jobs:
  test:
    runs-on: ubuntu-latest
services:
  elasticsearch:
    image: elasticsearch:8.19.1
    ports:
      - 9200:9200
    env:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ELASTICSEARCH_SSL_ENABLED: "false"         # <--- add this line
      http.ssl.enabled: "false"                  # <--- add this line
    options: >-
      --health-cmd "curl -f http://localhost:9200/_cluster/health?wait_for_status=yellow"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install
      working-directory: api

    - name: Wait for Elasticsearch
      shell: bash
      run: |
        echo "Waiting for Elasticsearch..."
        for i in {1..60}; do
          if curl -sf http://127.0.0.1:9200/_cluster/health >/dev/null; then echo "Elasticsearch is ready"; break; fi; sleep 1; done

    - name: Run tests
      run: npm run test
      working-directory: api
      env:
        NODE_OPTIONS: --experimental-vm-modules